# Generated by Django 5.1.4 on 2025-02-22 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Employee",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "first_name",
                    models.CharField(
                        help_text="Введите Имя", max_length=50, verbose_name="Имя"
                    ),
                ),
                (
                    "last_name",
                    models.CharField(
                        help_text="Введите Фамилию",
                        max_length=50,
                        verbose_name="Фамилия",
                    ),
                ),
                (
                    "patronymic",
                    models.CharField(
                        blank=True,
                        max_length=50,
                        null=True,
                        verbose_name="Отчество сотрудника:",
                    ),
                ),
                (
                    "position",
                    models.CharField(
                        blank=True,
                        help_text="Укажите должность сотрудника",
                        max_length=100,
                        null=True,
                        verbose_name="Должность",
                    ),
                ),
            ],
            options={
                "verbose_name": "Сотрудник",
                "verbose_name_plural": "Сотрудники",
            },
        ),
    ]
